import React from "react";
import { Avatar, Empty, Donut, MiniBar, Panel, Pill, Spinner, StatCard } from "./UI";
import { STATUS } from "./constants";
import { fmt, fmtDate } from "./helpers";

export default function CustomerHome({ profile, orders, loading, totalSpent, deliveredCount, pendingCount, cartCount, cartTotal, spendingByMonth, orderStatusCounts, setSection }) {
  return (
    <div style={{display:"flex",flexDirection:"column",gap:16}}>
      <div style={{background:"linear-gradient(120deg,#0E2A23 0%,#1a4d38 100%)",borderRadius:14,padding:"24px 28px",display:"flex",alignItems:"center",justifyContent:"space-between"}}>
        <div><div style={{fontSize:12,color:"rgba(255,255,255,.55)",marginBottom:4}}>Welcome back 👋</div><div style={{fontSize:22,fontWeight:700,color:"#fff"}}>{profile?.name||"Customer"}</div><div style={{fontSize:12,color:"rgba(255,255,255,.5)",marginTop:4}}>{profile?.email}</div><div style={{display:"flex",alignItems:"center",gap:8,marginTop:10}}><span style={{fontSize:11,background:"#C6A84B25",color:"#C6A84B",padding:"3px 10px",borderRadius:20,fontWeight:600}}>{profile?.reputation?.rank||"Starter"}</span><span style={{fontSize:11,color:"rgba(255,255,255,.4)"}}>Trust score: <b style={{color:"#C6A84B"}}>{profile?.reputation?.score||0}</b>/100</span></div></div>
        <Avatar name={profile?.name||"?"} size={60} bg="#C6A84B" color="#0E2A23"/>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><StatCard label="Total Spent" value={fmt(totalSpent)} sub="All paid orders" accent="#1D9E75" icon="💰"/><StatCard label="Total Orders" value={orders.length} sub={`${deliveredCount} delivered`} accent="#C6A84B" icon="📦"/><StatCard label="Active Orders" value={pendingCount} sub="In progress" accent="#185FA5" icon="🚚"/><StatCard label="Cart Items" value={cartCount} sub={`${fmt(cartTotal)} total`} accent="#D85A30" icon="🛒"/></div>
      <div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr",gap:14}}><Panel title="Spending Over Time" subtitle="Monthly breakdown">{spendingByMonth.length>0?<MiniBar data={spendingByMonth} color="#1D9E75" height={90}/>:<Empty icon="📊" text="No spending data yet"/>}</Panel><Panel title="Order Breakdown"><Donut label="orders" slices={[{label:"Pending",value:orderStatusCounts.pending||0,color:"#C6A84B"},{label:"Processing",value:orderStatusCounts.processing||0,color:"#185FA5"},{label:"Shipped",value:orderStatusCounts.shipped||0,color:"#0c5a9e"},{label:"Delivered",value:orderStatusCounts.delivered||0,color:"#1D9E75"}]}/></Panel></div>
      <div style={{display:"grid",gridTemplateColumns:"1.5fr 1fr",gap:14}}><Panel title="Recent Orders" action="View all →" onAction={()=>setSection("orders")}>{loading.orders?<div style={{padding:"20px 0",textAlign:"center"}}><Spinner/></div>:orders.length===0?<Empty icon="📦" text="No orders yet — go shopping!"/>:orders.slice(0,5).map((order,index)=><div key={order._id} style={{display:"flex",alignItems:"center",gap:12,padding:"10px 0",borderBottom:index<4?"1px solid #e8ede9":"none"}}><div style={{width:38,height:38,borderRadius:10,background:STATUS[order.status?.toLowerCase()]?.bg||"#f1f1f1",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>{STATUS[order.status?.toLowerCase()]?.icon||"📦"}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:500,fontSize:12.5}}>Order #{order._id?.slice(-6).toUpperCase()}</div><div style={{fontSize:11,color:"#7a8c7e"}}>{fmtDate(order.createdAt)}</div></div><div style={{textAlign:"right"}}><div style={{fontWeight:600,fontSize:13}}>{fmt(order.totalPrice)}</div><Pill label={order.status}/></div></div>)}</Panel><Panel title="Quick Actions"><div style={{display:"flex",flexDirection:"column",gap:10}}>{[{icon:"🛍",label:"Browse Products",action:()=>setSection("shop")},{icon:"📍",label:"Find Nearby Vendors",action:()=>setSection("nearby")},{icon:"📦",label:"Track My Orders",action:()=>setSection("orders")},{icon:"⭐",label:"Write a Review",action:()=>setSection("reviews")},{icon:"💬",label:"My Messages",action:()=>setSection("messages")},{icon:"👤",label:"Edit Profile",action:()=>setSection("profile")}].map(item=><button key={item.label} onClick={item.action} style={{display:"flex",alignItems:"center",gap:12,padding:"11px 14px",borderRadius:9,border:"1px solid #e8ede9",background:"#fafbfa",cursor:"pointer",fontSize:13,fontWeight:500,color:"#1a2b1f",textAlign:"left"}}><span style={{fontSize:18}}>{item.icon}</span>{item.label}<span style={{marginLeft:"auto",color:"#7a8c7e",fontSize:14}}>›</span></button>)}</div></Panel></div>
    </div>
  );
}
